Add New Xray Scan Logic
jfrog/jfrog-visual-studio-extension pull request #27
Opened 2022-09-28 19:32 UTC by talarian1

Adds support for an Xray scan with context: JFrog platform project name or list of watches.
Adds support for authentication with an access token.
Adds UI field of "fixed version"

2022-09-29 08:13 UTC, eyalbe4 requested changes

2022-09-29 08:13 UTC, eyalbe4 commented on JFrogVSExtension/UI/Panel/DataService.cs
> +        private Artifacts ParseCliAuditJson(string scanResults)
Let's add a new-line before this method.

2022-09-29 08:13 UTC, eyalbe4 commented on JFrogVSExtension/UI/Panel/DataService.cs
> +                artifacts.artifacts.Add(artifact);
Line is misaligned.

2022-09-29 08:13 UTC, eyalbe4 commented on JFrogVSExtension/UI/Panel/DataService.cs
> +
Redundant new-line.

2022-09-29 08:13 UTC, eyalbe4 commented on JFrogVSExtension/Utils/HttpClient/HttpUtils.cs
> +        public static async Task GetArtifactoryPingAsync()
Let's add new-lines between all the methods in this file.

2022-09-29 08:13 UTC, eyalbe4 commented on JFrogVSExtension/Utils/HttpClient/XrayHttpClient.cs
Redundant new-line.

2022-09-29 08:13 UTC, eyalbe4 commented on JFrogVSExtension/Utils/HttpClient/XrayHttpClient.cs
> +
Redundant new-lines.

2022-09-29 08:13 UTC, eyalbe4 commented on JFrogVSExtension/Utils/HttpClient/XrayHttpClient.cs
> +                                                                        string.Format("{0}:{1}", user, password))));
Let's fix this line's alignment.

2022-09-29 08:13 UTC, eyalbe4 commented on JFrogVSExtension/Utils/ScanManager/ScanManager.cs
> +        public static ScanManager Instance
Let's add new-line between the methods in this class.

2022-10-12 09:20 UTC, RobiNino requested changes
Looks good!

2022-10-12 09:20 UTC, RobiNino commented on JFrogVSExtension/UI/Panel/DataService.cs
> +                // Handel security issuses (violations and vulnerabilities)
Handel -> Handle.

2022-10-12 09:20 UTC, RobiNino commented on JFrogVSExtension/UI/Panel/DataService.cs
> +                    // Handel licenses information
Handel -> Handle.

2022-10-12 09:20 UTC, RobiNino commented on JFrogVSExtension/UI/Panel/DataService.cs
> +                            if (!artifacts.ContainsKey(artifactId))
Create a function to remove duplication with line 206

2022-10-19 12:42 UTC, merged